<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.0.1 setup script
 * Date: Thu, 29 Aug 2019 20:03:58 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'Polloasado';

/* End of servers configuration */

$cfg['blowfish_secret'] = '+o%MPKM(g&T=[=Fwgqs|VS]1)n7+GnE5';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>